export const servicesData = [
  {
    icon: "/assets/images/service-icon-1.webp",
    title: "Quick Delivery",
    description:
      "Optimized for a smaller build size, faster dev compilation and dozens of other improvements.",
  },
  {
    icon: "/assets/images/service-icon-1.webp",
    title: "Quick Delivery",
    description:
      "Optimized for a smaller build size, faster dev compilation and dozens of other improvements.",
  },
  {
    icon: "/assets/images/service-icon-1.webp",
    title: "Quick Delivery",
    description:
      "Optimized for a smaller build size, faster dev compilation and dozens of other improvements.",
  },
  {
    icon: "/assets/images/service-icon-1.webp",
    title: "Quick Delivery",
    description:
      "Optimized for a smaller build size, faster dev compilation and dozens of other improvements.",
  },
];

export const booksData = [
  {
    id: 1,
    rating: 4.5,
    category: "Biography",
    name: "Such a Fun Age",
    author: "Bill Bryson",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/hero.webp",
  },
  {
    id: 2,
    rating: 4.5,
    category: "Biography",
    name: "Such a Fun Age",
    author: "Bill Bryson",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/hero.webp",
  },
  {
    id: 3,
    rating: 4.5,
    category: "Biography",
    name: "Such a Fun Age",
    author: "Bill Bryson",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/hero.webp",
  },
  {
    id: 4,
    rating: 4.5,
    category: "Biography",
    name: "Such a Fun Age",
    author: "Bill Bryson",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/hero.webp",
  },
  {
    id: 5,
    rating: 4.5,
    category: "Biography",
    name: "Such a Fun Age",
    author: "Bill Bryson",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/hero.webp",
  },
];

export const featured = [
  {
    id: 1,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "/assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 2,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "/assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 3,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "/assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 4,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "/assets/images/seller-1.webp",
    rating: 4.5,
  },
];

export const sale = [
  {
    id: 1,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
    leftBooks: 10,
  },
  {
    id: 2,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
    leftBooks: 10,
  },
  {
    id: 3,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
    leftBooks: 10,
  },
  {
    id: 4,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
    leftBooks: 10,
  },
];

export const ratedCard = [
  {
    id: 1,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 2,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 3,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 4,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 5,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 6,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 7,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 8,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 9,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 10,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 11,
    name: "A Heavy Lift",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
];

export const sellerData = [
  {
    id: 1,
    name: "Story of Everest",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Story of Everest",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Story of Everest",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
  {
    id: 4,
    name: "Story of Everest",
    author: "John Doe",
    price: 12.99,
    discount: 14.99,
    img: "../assets/images/seller-1.webp",
    rating: 4.5,
  },
];

export const testimonialData = [
  {
    id: 1,
    name: "Valerie J.",
    role: "CEO",
    logo: "/assets/images/bing.webp",
    para: "Like this histudy, vulputate at sapien sit amet, auctor iaculis lorem. In vel hend rerit nisi.",
    avatar: "/assets/images/avatar-4.webp",
  },
  {
    id: 2,
    name: "Hannah R.",
    role: "CEO",
    logo: "/assets/images/hubs.webp",
    para: "Like this histudy, vulputate at sapien sit amet, auctor iaculis lorem. In vel hend rerit nisi.",
    avatar: "/assets/images/avatar-4.webp",
  },
  {
    id: 3,
    name: "Pearl B. Hill",
    role: "Marketing",
    logo: "/assets/images/bing.webp",
    para: "Like this histudy, vulputate at sapien sit amet, auctor iaculis lorem. In vel hend rerit nisi.",
    avatar: "/assets/images/avatar-4.webp",
  },
  {
    id: 4,
    name: "Mandy Wood",
    role: "Designer",
    logo: "/assets/images/hubs.webp",
    para: "Like this histudy, vulputate at sapien sit amet, auctor iaculis lorem. In vel hend rerit nisi.",
    avatar: "/assets/images/avatar-4.webp",
  },
];

export const blogs = [
  {
    id: 1,
    category: 'category',
    time: '10 min read',
    title: "Blog Title",
    author: "John Doe",
    date: "Mar 17 2026",
    img: "../assets/images/seller-1.webp",
    para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus.",
  },
  {
    id: 2,
    category: 'category',
    time: '10 min read',
    title: "Blog Title",
    author: "John Doe",
    date: "Mar 17 2026",
    img: "../assets/images/seller-1.webp",
    para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus.",
  },
  {
    id: 3,
    category: 'category',
    time: '10 min read',
    title: "Blog Title",
    author: "John Doe",
    date: "Mar 17 2026",
    img: "../assets/images/seller-1.webp",
    para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus.",
  },
  {
    id: 4,
    category: 'category',
    time: '10 min read',
    title: "Blog Title",
    author: "John Doe",
    date: "Mar 17 2026",
    img: "../assets/images/seller-1.webp",
    para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus. Nullam nec metus vel ante feugiat finibus.",
  },
];